### ISSUE TITLE
Implement unit tests for Chatter.CQRS

### ISSUE THREAD

**Issue by brenpike** [brenpike/Chatter#19]

**Comment by Greven145** [comment]
Feel free to assign this to me

**Comment by brenpike** [comment]
My plan was to have a "test" folder at the path below (along side the src folder):
https://github.com/brenpike/Chatter/tree/master/src/Chatter.CQRS

thoughts?

**Comment by Greven145** [comment]
That works. I'll make a Test folder in the solution to keep them separate
________________________________
